# Generated by Django 3.0.6 on 2020-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200524_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='media/user_default.png', upload_to='images/'),
        ),
    ]
