# Generated by Django 3.0.6 on 2020-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200527_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='user_default.png', upload_to='images/'),
        ),
    ]
