# Generated by Django 3.0.6 on 2020-05-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
