# Generated by Django 3.0.6 on 2020-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='This message is just test', max_length=100),
            preserve_default=False,
        ),
    ]
