# Generated by Django 3.0.6 on 2020-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200517_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
