# Generated by Django 3.0.6 on 2020-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
